
export const GET_COMPLETED_REQ="GET_COMPLETED_REQ";
export const GET_COMPLETED_SUCC="GET_COMPLETED_SUCC";
export const GET_COMPLETED_FAIL="GET_COMPLETED_FAIL";

export const GET_PENDING_REQ="GET_PENDING_REQ";
export const GET_PENDING_SUCC="GET_PENDING_SUCC";
export const GET_PENDING_FAIL="GET_PENDING_FAIL";

export const POST_PENDING_REQ="POST_PENDINGREQ";
export const POST_PENDING_SUCC="POST_PENDING_SUCC";
export const POST_PENDING_FAIL="POST_PENDING_FAIL";